services:
  - type: web
    name: shiny-rachel-blog
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SITE24X7_APM_LICENSE_KEY
        sync: false
